import type { ReviewPreview } from "./review-types";

const commonPatch: ReviewPreview["files"][number]["patch"] = [
  { kind: "context", oldLine: 42, newLine: 42, text: "export async function loadWorkspace(id: string) {" },
  { kind: "deletion", oldLine: 43, text: "  return client.get(`/workspaces/${id}`);" },
  { kind: "addition", newLine: 43, text: "  const workspace = await client.get(`/workspaces/${id}`);" },
  { kind: "addition", newLine: 44, text: "  return normalizeWorkspace(workspace);" },
  { kind: "context", oldLine: 44, newLine: 45, text: "}" },
];

export const REVIEW_PREVIEWS: ReviewPreview[] = [
  {
    id: "github-jugglework-desktop-1842",
    provider: "github",
    hostname: "github.com",
    owner: "jugglework",
    repository: "jugglework-desktop",
    number: 1842,
    title: "Add revision-safe workspace synchronization",
    body: "Makes workspace refreshes revision-aware and prevents stale responses from replacing a newer local snapshot.",
    author: "Maya Chen",
    authorInitials: "MC",
    relationship: "requested",
    updatedAt: "18m",
    baseBranch: "dev",
    headBranch: "maya/revision-safe-sync",
    headRevision: "8f3b2c1",
    additions: 286,
    deletions: 74,
    changedFiles: 9,
    comments: 4,
    pinned: true,
    labels: ["desktop", "sync"],
    summary: [
      "Introduces monotonic revisions for workspace refresh responses.",
      "Ignores late network responses after the active workspace changes.",
      "Adds regression coverage for overlapping refresh and reconnect flows.",
    ],
    files: [
      { path: "apps/app/src/react-app/shell/route-workspaces.ts", additions: 82, deletions: 21, language: "TypeScript", patch: commonPatch },
      { path: "apps/app/tests/workspace-routes.test.ts", additions: 64, deletions: 3, language: "TypeScript", patch: commonPatch },
      { path: "packages/types/src/workspace.ts", additions: 18, deletions: 6, language: "TypeScript", patch: commonPatch },
    ],
    checks: [
      { id: "lint", name: "Lint and formatting", detail: "All files passed", state: "success", duration: "1m 24s" },
      { id: "tests", name: "App unit tests", detail: "1,248 tests passed", state: "success", duration: "4m 08s" },
      { id: "mac", name: "macOS desktop build", detail: "Build is still running", state: "running" },
    ],
    threads: [
      { id: "t1", author: "Alex Wu", initials: "AW", body: "Should this comparison also include the connection generation so reconnects cannot reuse an older revision?", path: "apps/app/src/react-app/shell/route-workspaces.ts", line: 118, age: "12m" },
      { id: "t2", author: "Maya Chen", initials: "MC", body: "Added a generation guard and a regression test in the latest push.", age: "5m", resolved: true },
    ],
  },
  {
    id: "github-jugglework-server-927",
    provider: "github",
    hostname: "github.com",
    owner: "jugglework",
    repository: "jugglework-server",
    number: 927,
    title: "Harden connector token rotation",
    body: "Adds overlap-aware refresh token rotation and family revocation after replay.",
    author: "Leo Zhang",
    authorInitials: "LZ",
    relationship: "team",
    updatedAt: "1h",
    baseBranch: "main",
    headBranch: "security/token-rotation",
    headRevision: "c41a7dd",
    additions: 412,
    deletions: 109,
    changedFiles: 14,
    comments: 7,
    labels: ["security", "oauth"],
    summary: [
      "Rotates opaque refresh grants while preserving a short concurrency overlap.",
      "Revokes the token family when an expired predecessor is replayed.",
      "Adds request-reference diagnostics without logging credential values.",
    ],
    files: [
      { path: "src/auth/refresh-grants.ts", additions: 144, deletions: 42, language: "TypeScript", patch: commonPatch },
      { path: "src/auth/refresh-grants.test.ts", additions: 173, deletions: 8, language: "TypeScript", patch: commonPatch },
    ],
    checks: [
      { id: "security", name: "Security policy", detail: "Policy checks passed", state: "success", duration: "48s" },
      { id: "integration", name: "OAuth integration", detail: "2 scenarios failed", state: "failure", duration: "3m 31s" },
      { id: "deploy", name: "Preview deployment", detail: "Waiting for integration tests", state: "queued" },
    ],
    threads: [
      { id: "t3", author: "Priya Shah", initials: "PS", body: "The overlap branch appears to issue a successor before the compare-and-swap commit. Could two nodes both win here?", path: "src/auth/refresh-grants.ts", line: 203, age: "34m" },
    ],
  },
  {
    id: "github-jugglework-desktop-1834",
    provider: "github",
    hostname: "github.com",
    owner: "jugglework",
    repository: "jugglework-desktop",
    number: 1834,
    title: "Polish automation history filters",
    body: "Improves compact filter layout and keeps silent refreshes from flashing the entire page.",
    author: "Nora Li",
    authorInitials: "NL",
    relationship: "authored",
    updatedAt: "3h",
    baseBranch: "dev",
    headBranch: "nora/automation-filters",
    headRevision: "de82f01",
    additions: 95,
    deletions: 48,
    changedFiles: 4,
    comments: 2,
    draft: true,
    labels: ["automation", "ui"],
    summary: [
      "Moves history filtering into a responsive grid.",
      "Uses silent refreshes after row actions to prevent full-page loading flashes.",
    ],
    files: [{ path: "apps/app/src/react-app/domains/automations/automation-page.tsx", additions: 71, deletions: 41, language: "TypeScript React", patch: commonPatch }],
    checks: [
      { id: "lint", name: "Lint and formatting", detail: "All files passed", state: "success", duration: "1m 02s" },
      { id: "tests", name: "App unit tests", detail: "All tests passed", state: "success", duration: "3m 47s" },
    ],
    threads: [
      { id: "t4", author: "Sam Rivera", initials: "SR", body: "The compact layout looks much better. Could the date range retain its value when switching tabs?", age: "2h", resolved: true },
    ],
  },
  {
    id: "github-jugglework-docs-316",
    provider: "github",
    hostname: "github.com",
    owner: "jugglework",
    repository: "docs",
    number: 316,
    title: "Document external MCP OAuth setup",
    body: "Adds setup and troubleshooting guidance for external MCP clients.",
    author: "Jamie Park",
    authorInitials: "JP",
    relationship: "reviewed",
    updatedAt: "Yesterday",
    baseBranch: "main",
    headBranch: "docs/external-mcp-oauth",
    headRevision: "2b6c143",
    additions: 138,
    deletions: 12,
    changedFiles: 3,
    comments: 5,
    labels: ["documentation"],
    summary: [
      "Documents discovery, OAuth callbacks, PKCE, reconnect, and organization pinning.",
      "Adds a support checklist for request and reference IDs.",
    ],
    files: [{ path: "packages/docs/cloud/run-in-the-cloud/cloud-mcp.mdx", additions: 108, deletions: 10, language: "MDX", patch: commonPatch }],
    checks: [{ id: "docs", name: "Docs build", detail: "Build passed", state: "success", duration: "2m 16s" }],
    threads: [
      { id: "t5", author: "Jamie Park", initials: "JP", body: "Updated the callback matrix and clarified the difference between setup-only and verified clients.", age: "Yesterday", resolved: true },
    ],
  },
];

export function reviewPreviewById(reviewId: string | null | undefined) {
  return REVIEW_PREVIEWS.find((review) => review.id === reviewId) ?? null;
}
